apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pihole
  name: pihole
spec:
  storageClassName: "longhorn"
  volumeName: pvc-dfe3e97d-cefd-4239-aeea-37cc8414460d
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
