apiVersion: v1
kind: Service
metadata:
  labels:
    app: signal
  name: signal
  namespace: signal
spec:
  selector:
    app: signal
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
