apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentik-server
  name: authentik-server-ports
  namespace: authentik
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9443"
      port: 9443
      targetPort: 9443
  selector:
    app: authentik-server
