env:
  - name: authentik.secret_key
    valueFrom:
      secretKeyRef:
        name: authentik-passwords
        key: authentik
  - name: authentik.postgresql.password
    valueFrom:
      secretKeyRef:
        name: authentik-passwords
        key: postgresql
  - name: postgresql.password
    valueFrom:
      secretKeyRef:
        name: authentik-passwords
        key: postgresql
