---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgCwFMF0mXAtFCTEhQ1g/Zn69UT45s4e+iCb7qjbh9HB2yQSUqTAxyMeVlAiOkPZa54mOg24t3nKMK2SOA8WJcALeIEfixBYzda3DFXGO0zxnLfXWilYox9vj4f2NfQmP6CKNNwIplAweX1yBgK0AATMGiSDBFo5PcSKCdxhlO9w0gS1RchjCbjiF3ZFtRo6Q8sH5Vpqq0ClxNo4Ie15fHuU1ZJL1+wrg3TSeDQAmVPaCmtLDn4sNDDh32tCcF5ebnrCH7tBP0NefUFHkMqiTv2KovOu8KE73ShHpxhG9IJ7trL91EI7mKRiO6TPGwvtB/DCJMNMTDvH3wcT5u0iw3BaB6thSil4vHbwpBsRlLMfAVwJGsCqWgp5JuCSv1fjxrH1LVmSfrS+sUUVUlgB3yEOkfGfnfbQveASparnZdqNJXeLMf98jpu/RlWX1owp7gJLddG/jRWssIgps382PQjv1JmfizBBXDfI9PyaIKjkwppufrpW5DVBsPZ0cfgwAcgcPDFYqOoPIyV/xT+3Cew13NUhmktsTlBibC+HR1emRoC1vasKX94f/+PFUb+w2UDMF8DkFexRUxBVDT8fCuUe2hkVFZVJ/PzT4WgOr2iKLAJ1jjSHhoJMLNH9srF+S+qf503+a1VXVsV97EqDsFnf2z49od3kXJhaHfRk7AMq7YERCsqElPtWB3EuiNT+BIoxhaZmiip1OTmEJDr2arD/vGU2QCcuz8uxDCljX3/6pWnYeA6+eB+TBHj1Jakw5vSRAmmlV6YRF12HPc9lpPntec6ZyWluZ9vjKZb3ipFnlISz3dlZvPLoaVMRIcUObUcuxQmj5nOc9bIg6jrPW1iFNHo/eTdlHH8uKrnP597GnkwuWKHZS44AmbYYe70J/q9iKamczjTiLUiJ0X7VcDbIjUnukigWfIvXQgUVEDVJ9FmGT79MfH3ektFMjOfjCHKD5ExeNlnu1xQm7I1Ds/XLadiQpsGuuP72Q/wClo9D+AVkpvF1KJQhcMYg2XN2jmoecSS+0A5PgkwJlOrciNjDJa2V/+sMwUJtV3OTgXwTJyOcSG0xf0c/DbuKJZVZYa3jEbuZcMuuoU6+WfDSeC3WtsRNvorMz6c3FJcw93ElcYjPitJ7q41p0AlEp4FS0Xj0xUDUj4bgZ7M97ytHj6HCd/5owZkCYuvYn2j0LGnaIChb/SGMckeIl4gqKAc5Jt5CVtuMy37spD2vHgOEvhAvewbcrR80NR/UTQfJ5eT7FTeAptp9PIsQj5ak/rBE43MfjIoLNqhncLjF8pXp9RdfUsvtiKAA1eBOU/fNHuBIH3gRW0PjkqlXtHInCmH/xm28KeawmS5z4LlOFQ20rqUFGBIKHiCvNmKFBfYrESFVwZs=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret-values
      namespace: authentik
