---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgAMpHD1OndawmbCq2wzaKWf0T/zgI4fqy3zsgRUzcUIRfg8/6tBwgEXOsfX0l/mIkxpOCsiIl7ghS0C6KAcPKnOqLy9XcYP1LNQm/+k0gCr7fhW7Z9+Aw0kevNRYZ82Un3oUi4DkPexP+uCrgz7Gn/0cUMnWvLr9mMOvweHZHM3UyvIF9MnNrjM3xfndjloS/b68Qm6ghD+vNNsUQgS+3urDAeH+bwTbQswVEu/HNJUl8xPnIlto4Dj7P3wgF3C5dAqd7FrRqQ6ZMITqLEq+XPt9PF/O02vGZAVwxqvCiSVUypQPvypg4gtleh19hFwGPIuVprq7CihzGrffAP7HWGgEEOF/rOXQet73TWjHGovP2zjyye0oRKqzsordkamoUg1kuSzkhc/1/QCbK28PIwWNiVVzVXN722tSehxkhiZfzDtJzt+wdiab/3MOjcbRRWjIOMY7kZsWV7upBnib4DoTwgcGeWY9iPvZHk5GcC0GAdgoW0QHllD5OPlRNzI5d+GWk2V1RTvIZ84Zq2Ohn1PZ155fKB5QTKUdPQyvNrEcQhePQtGj8QkR53gfK0JrIS44CAJWZKgHkYWOHg2bec0BbmMgzsKs9hR/qVzuUWV1ioKPHBnmVos3rRzYu7IxFxojke9hJKodv6cvE5X3C0CWDWMSH5P59HG4xNliMHBUbyUfOwGb6EC/4az2t9Ypp7dtQl60V7QneL9tVNwNhEIHtxEzH0tDTsMmML8nu14haZo+zzVYaslJyZwQPPLlef0UT/rRN59u6Nb8qtAcokP+Q1F1xxshaU3/lf5u1i6yiaY+r6BmgmCoartsyNyH198wdnXOeQdd2bY09QLGZP5PLBvTXVxiN1CYWtdlmuPuOb6nUCh4CqwkFo75m/2LwxugKeen3SjQcfxzPAT0s+TOqN177GK/ZRx/5isRSl+7MjE1ZD8356q7i8ZQH13ougRYN1Jt0V1MEx956BlrCNtloscYRPGwqOc+p3uJe7xnp/nLNDCLNCYQ9zFbPxkvUgjBIX04aBvE9JeqNQ9MO3vkLrk3pQjr5aoE7oh3sZGkeXIZ/ssKxBM4ZQPaLUeXaeS3+eHKc+YsjCvFvT/H1LFzD+9/ddmn7AhFJINGy1dY/CKWil3ANfJGsMV1lV0eUSQq7mOHySCvIfI1Eyj/B0UXHm8ariH9Vo2OmhNOppzdEBU5GMklO+6bF772J8k4TA7xtJSnUsfon8SFonkYDYwKyMktnUiXQ0q9fZqGHMN11sAXKq+217tKbrVM2bMEuiWtJ2hqT+ABwrnKdtEBRHyhRS+SzvMX5wecgzTsIfrGh4=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret-values
      namespace: authentik
