apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "uptime-kuma"
  name: "uptime-kuma"
spec:
  storageClassName: "longhorn"
  # volumeName: "pvc-ac13fb96-5c2c-45cc-bfe4-f0f74eac93b0"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"