apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "uptime-kuma"
  name: "uptime-kuma"
spec:
  storageClassName: "longhorn"
  volumeName: "uptime-pv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
