apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "immich"
  name: "immich"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2000Gi"
