---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgAhi8Kt5P/975W/72/4rBZBXxLiZg1Zz+rgfEXgxdXIpD5bKkDnX1Bk10AQlMuCfxG7Yi3e/tUiEylPSxFv5dl1jlrU6/7GTSJx/34Pha7Ppobyk+L5MK0kIkRkyLYYHSpESEGznEUgZ51e/jyIiXnhTr6G8OaUXof4VQmLLQaPlqLpJexInu/zqC/42DL3EjM1WwlR/c2l7ZCW939sH8Vjvn1k1hNIaq/k20ShJSlpSPaJoeBqAQrrG1FmasxtxGUGGi6SV5G4jXxaOUVh9ddLVw+eBAQumrffu/KvzTImxCh/I6T4mtRIoPM2SS6CzSflemE6jFeMKHPqT1+7LgS+yBEUlUK0Y2Y/0tUDF7UTepKcgiWo4oI3UUD3XFilBc3UKMwxbc9m4bjxbjhhOyALgwAl5/6tzd6DT16e7S1pnXi8RxXpSzf0/fy7kg9U4vA3uF5R+FpI5opSHWJViDo55CUKoFyoFGhfnnMd8hxS0ih7EWiDr+zXRS52LpQ8GBY5GY3ZBSnZtdKQ2o40RYYBGggpcgweFbubKg07v95a1xpP02DVokGQMVH/bfajgheDf9eVz1LB4ISGjxq3oxpcsFcJEUDofZNRcm9yWwDF+hlBmoQCv5YSAmSk1/gRL01YA81tYRtjIHmNm6gT9hzUpxJp6hXSYYjDeqvvWi1rbn5Iw3bTJSWUp9h2a/piUJUDsTFDK3W79xuKRJ0VNVE9JAMEc3HJw3NvEHyKLyItDHdBDJpSuc19HRa5WkwBo8Uqg/rAKxJcWtERnMLujYY66RJWhnh4gnq7Ld32xRb3xJKwPdPaKfUt5uaMS3XeDAmklwpRrmfYjCSqB7QmF4GAd0lMRT4QnVnKYDOd5K/vrDsJgDw=
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret-values
      namespace: immich