---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obsidian-livesync-couchdb
  namespace: obsidian-livesync
spec:
  encryptedData:
    adminPassword: AgCSESFpSFFCvSz1Lf61q/f0XIzNnA5YtecObezCAxUyf+svwbkPob+fNrsfIufUEXFIAZbIbdduurzMbIIJUkRfhGeLBad1QPr8VWmyW96pzqj23g+mSo8G/PRFQ5yE5WPfg5is9Q5GcLBwkJJ/u8F66kxnGCpExuaa3aZzD+V8IrIbEfbGnvyU0apBJrex4T6qh2L13KH1ZyeWOAjgpATQKXq1lRVK5POax6OKnn92ssDSMQ97zrvFR6FzxlWEoGTBkAiqWs8h8onn6kolakptIY6XRjw1B5ph81a965ergLCew/8aa9bHtl6k1Whp8lyouOXS4d5fGD2eq/z2Lbk1bjnkP0FLdPPshOY0WVC3alNBk3uJJEWtP96xdLS0a+B5VMDoQaMg6e0GnYQttPew1o76sIcX30wcicNBCJXobmpnXcNHzJ1iP0/xyZsAkCljh0q8pS62FR4HJLAvz9gDLnrMhuLJronZvoMOGqEKK/jOqXmoNjiyRrzOr+m8RLZ6BDAfqrldelPpBOqRvN+Cro8bPJEwj3lhTjtY2eCMYUN8OXvweaUICAAN1fc8ieGd8byZDIKJC5cQ+49MJT1kwnC/CQ0Hs3A0rdHjyGFpZPHwzXI/uCN35rWtll9QRXVeTNjRAkTseStedk+wYyCxE6LuyNjGOxLTjBq2PGm7grhieRsqpwO6uieTFD8vOKsx1np2h1IPtKyeea5MVw==
    adminUsername: AgCPUSoCtb/SM7BPhvlFMItQtTCPT/ETmy9oWw6LdwGv1kIjg6iHvW16KGsB+3y6QIcb0j5q5XIE1RWGgaDOerTW2vGmoMAqMwWU5ADypXImfCOxIiC4pyGeqK2syev6jPQM95lUdvXTs+8HFGP9zGnxohp1e/TQj2NWxsWlTea8YcKqekOk099Ut36GOO52WUKu0gg/kTOod0DU0mXgxdjtKVUa2kfj3yWZezixF0a6sAd8xCgczhMu3yTyU08oA1tB6IWWsz/ubwesILbpTcutZXU4iOw1rfRY+jloCiw4WSDALvvO0Eeby4KxesmXQrsOqqBj1b59fafeUoRuqvuziXHicWhl6+6QS2+Xsg1f/2t6Ep+XIz3ttW8+hRj/Crz47kaZP05le6EoqRviOQmez1jrCqHZne4ucryZyOxMtkxlIas2I+SC/63JpIeO7PB5mmcwk3/2q6opI4WcFvYsBdOFwiSSBmcWYHhMsjSXg5E3CZk5kfuzC1h5QtfRDC7l6hiPGD01fNnh56TlVRsBbCjUydsVgnZ8WNM9hhngr8nUgby9uashObHhS5H3UVpJv878JpspzpjzYZT1wRLa/+OJ4YvpBNFvhFPXZ9Eut4XbG5zEFbDxfA5DGsiQGTNYfTvyNSnMuUmZGcZrQZi22A6U2Bq3afwl/R/KUbDQfAvJwRacPLe92Kt25NHjOOtXXl73Yj9L6Bqy
  template:
    metadata:
      creationTimestamp: null
      name: obsidian-livesync-couchdb
      namespace: obsidian-livesync
    type: Opaque
