---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obsidian-secret-values
  namespace: obsidian-livesync
spec:
  encryptedData:
    values.yaml: AgAxwtilUFxF6RntFuZhmu1AQQ2XdysDGM9B/dQIHe0B73N4BHVf/0PdhZIP3MDnceD5MvfoBP7/nIRzG6QqiFqWNFA+Ur6eSMknGXLeGiIx1cMCn/ahlYBARIj9ML51zdygHNzW2D/ZYhkD2bkymQQswmFszr+FliWNeFncdS/BA6oydx85E0rKZ7g0ZszCsyZMwCcD+4YZvNI4x74N7B6CLH8CqQjE8yx221naF0AyhKiK+ecPCRHTWVvsvm82C2YSQ8DhZ5bO3RFsFAgfGbZmW8y+iUYSZBu4Gi28HFQ29AnghMu/oSCmwwZv2WPVzUrljO2sqSl0odovrvoZovTB4ySZI3DABPj7FLlvTWxX7AZx0g4tOCP+9kQtx0v0WOfPXuDh319b0Qgzic/4A/KOOYGl/SFlJWH7k0IlhB954o5WbYPn6aMH/dS7w/H5VBHNnjDPjAYr7S9rW2iyIXBx3JXX2zSNYz6nnpMDEOaY+W46SkPZO3Hg25HJHEqK1ORErfrwcppRzXN5QAtCO2rz35LDFboZE+HcIAkAr2w6Bb9GrweyR10vnRJGj+zduPV2w1b3mtjHCRDwmPJ6bnaZ34N1bLZBhVx+8PTexjj9u14mo7CdEJ9pDe14fp9jPnAF5ZTdTlhNji1yl9oFuEp/Tw6Ve8UXj1zYFw4EoFLYyy8NlLaNrakc9/iY3ITHsdtPmx9HI/ER1e0tzuBNrLkmNT8dINDV8SKLv8J5Zbzp1UskP8siEWEO/EP4DTCAEsUEAdklhiJV1RCWHloh7Kg2p4wIMyCnkStOdbdk0BN0K3z2HKu4hJmHeRIjvJAkdOQ7OA+7RYDuBhxgW+IlrJJNQE0qJdCmP3Ff66tM6+22yKoh2/ZPjMzGIWHPQrmF7fTmm8w+Yu9PDT07i/Pdp3MaKC5v2Jldg2ByT5xe9DX4LZavekO/4JN4ptDG2ZgofP0aS9QoV4cPRE/5LfLD+2iQW2ZpCkgsXPs7wd8aJK1sFN+oTt9SKMowx+32EXazHZPZn0i3ZOaKZDuc4CBfXxvG0MuXqo//mVIzPsC118IfNNCXPiG0N50lq9iaKrPKXZHgFsuHwf7ac6DkgiJZgdc3yVTyVYGqhbvh3YlFoGX5ZM0mwwRFwQ0kMG2e3TX8Wmlb6d4W2AzQ5w2tvECFxVHq9TpMGVm48v5/wDw=
  template:
    metadata:
      creationTimestamp: null
      name: obsidian-secret-values
      namespace: obsidian-livesync
