---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-credentials
  namespace: pihole
spec:
  encryptedData:
    password: AgCbla2pg81lEn8zMwqrOulki5wH1vBJ5y/TrlcmlbxGBCbwENc+bGM/Wd6rpSrHIg1+GlS4bTuhcWYW0tv1PzvQ/12xL5HXdO5xDrWJwgwTlbY3Uo6q3O6DB5GIwVuw0Y7N1Qhq57Qf8Bv5dWXj9G6m1Evdpc2lUqEGFHJRLEhp7zvdsxDisx00v9OyteWBtC5IHvBxEo4LTBsYhS+6Tm+leuCZCJtprSwtsdcVAqcrkgt3QQZhi92/efC+nQgXbuMOHxSMHF/SpOPHpdWOiIKa/Ha6qugjvQecDM/tPzEdQ0Mmkcz14qaEXQZ770ebfIZKknwCafpaqPluuAo4SR9qarnWm+hxaAi6sg6APEjVWal4rfD9AHzijjWC2lapF9etYeZz2L3qNi6YzbHATV7vdK8UGXc9mymjSY2gn5nWb/xFAkaSid/tkwcri7/uX4z3d63o3jSfxEdnzb3Ap2Rejcf1RR5MOKAyoavOR/0vOtwppfaUaiZJp/PNEqjDcfBpQOKFVy+xZBlXTy0+8kgpc+KvbgDoCLl7bIpc1ygrL1ksH10tzdBH92gWmGZwQzZ8OfpuQlAbbGW5Prc12CvKjEv3t1Y7X6zktQbX251icA2zm0w3xLU4Sp02gBiLnZFylyjlC2TtWAlkPwYN7YmSdNd22B8CNZgDL8LmPl4a7p8IAiwCj3e/pGh5lhwSO58TXytSbYhZSOh32W/SJA==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-credentials
      namespace: pihole
    type: Opaque