---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-credentials
  namespace: pihole
spec:
  encryptedData:
    password: AgAvSBo4bbLWi+7NkRyirXc7VZb+es9jvlmUcauDsVpHHiny9L21OwX5LqtGCFpX9oobIih/s3lF3IISDdJiknJIkXfZ5G3XX4UwAPZD6mStf+mBxE49jk6I8rq77HtrtxQ94HT9AfnBoXzjQg11piXnQrFzrQdb8KBysMQIvhd01U/PMiRuc1waWZHc4NW5+bf1mcS1cfoc1Umke89C0OY8znPFNyxQLxGRhLz4J9QmAFZ3y4Ix0KdRjCWuIs+FosN94BCxjFu3Bp2H9/fRO4mlUD9lLB8QvMmyYZOvlWXGZ2u5jW6T46uA3A+o+Yixju1qBCpFcGFHdQgqf+9W8v1Rkcs4yE3aaAWOfoJQv5ZwmcjNby2Nlt8+QuJ+9GetzSZlgBqXViKS7Q3cjMHN5jOYLC5fjKd4peJ8xagycdbCPem0pKDzg5Rn+ZYZuNzFxAU2uhBQ3yzM3aOU4vVE3VQgqWMY1787u8D9NW3VQQadmo7d7pfczquTBHY6m6R/h5+eQ+IK7QJ/u5CISW8tBx6fZgalD6wvOHHRxVJVTEkSKrpNAhhHl5FPEf4O7XsqFAc/yvZ/FhSbbpgRLaCD5/CaYFrhaK+eQ1GtXqcX1t+Pg8L39e3GbiP5g1sR1csv50y46ncVvoZsvvf8606tNIr89yn2xUkHkOjvh1ZXW4YlnXaHJAvNE8vkD5G25DJyHRnfX0DifvNdaA==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-credentials
      namespace: pihole
    type: Opaque