---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCwmrdXrGBPeSmIt0WcHx02KaMTwd8PalSsV3LCOrSiAi+RliqXGsgnTldOK5mK8BOV0y/8r7H8fHVjK2rln4z9l6Y35F97fDyD6rbvZS5fgaaWM6OTdx4VweDdIrxPxvrBCZjtjN1nyGwcrLB976x4uzLUP/x146d4cbuFnbxpfxH9y3Uo8+Hm1LisWwsjmPJQ8tDXn9bW/CkgfV1C0CYvBZSzTle+GaiYmz2mE0+D/phZkDajXEtb0nC7CK8DFT9RnZkyslHhsbzSKv9N8njB3/+OEk3i7Ozrtm1wFlHHzul/3PHen6cru6wV4mEl3OjeItKQrh8DlEoVlTbsLDSdkV6IZWaevEzpestyPx1IxUZW3nMVPwMjzco58Rp9No2Qhv+a4PYChMQiJd/WOb7m3wJKlQArJdee0L14pO8elQdxdm6RX/qagpcqfY6ZAY0RVC7hn9aHOWe0VdjeATSkiqAWgJKSAWc6WNA0BA6JV7qnvkVUI9W69U+/8+caA8gy2geKJReMkBUAF8sst4UQwp02jVip9ln97HjnfI/q4uLiRzBKsyEGbpzSDNbIX9yP03Rd9cMItyu/6gTciueseFHkjKZ9M7CKDE63caHhaHVEpjRIWRTHkhfpqKBFEDKLeTV2mcri/dtebvFUxT+cbmqD2KW1QJd6dnCEsNSueuGb3Igr9Z5pVaFj2UyeQS+R+l5aId8Fe6C3u5lNchEQi0Xiik76KSbdn/e+lj3+JwtN36yTeCIrFFSGcFha5qwdTrNdpU5pV0qkO8VVYuOiLsVvfsqIStVrspr40cL7G7UboOxYKYKI0/Jlmvo=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-env
      namespace: renovate
    type: Opaque