---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgA4dMSMIfkiUdhVmQLD7+pjfdkuTZImWhkMqZEys0QpMYRbl39/EdgFvuUdqh7zYg8txSl65sAk4cFw+G4444gF+8WeQjH+VjXnEunhVzD1VvcNfFBtkDXDPxuy89oP6GD4y0ORZocSinOc8RIqTkXNosjGXljnCy1dn1ji04t3PRurOW9jXhhRcHkP+L3Yb4I0fyyS7QZGKp3RRZXfIWShs5hAC4WS4uIceumrQ5mwQXigaAzWfRYjnQix9mkT8c6WjGOH0n99QocoKxtYwKYkJ+OxIYFEWgnMxKxi1qYZ+b1eoDsVuJAJZiRVYm9yoZfeOOgz8k71ZWFRKIW1rhxle73pHdLI/CBTAW74+qoQmliX9xDQzphfSQ6yrrwi1NpVbB/AlxPxBakMBtQE3JrefRgiZWCpLQLtvlEo2/7KiUKmwmLU5Fhn4oSGZqY79SDmxSonLUfnE/9jqolg1ArbZUtfWjbSiYjddE/TInKtKNpG4LxtW2tFThIFj8D8yx1sseD2OaSxsylcK0N27dmSNi+wnClhrylfVkUSsadFtdK68SeURRk1g8YlvyzpHORnm2kKB99cPs5CsvZTDpzdCAro0zZERvkc9EnzBTnJw03JOhTrxqzDtMASXl53sjdNy76OFkDXEso35OXFqCcNKOgjeNjJwCMVQxs4QHaCoVcSI6zuZLC6yNrNAjjZEcO85jVTDrM7F+GzHzhKayAZvdB9G/4eibrOHc9zsLq+XtsRMXMe3XCsolORqzbp1k0lWrVpAVLbJTyiSEUwVFn5XFyf9/S+wsZ7Ce7LvuqjLTHJnurS+UUXVFsUBdo=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-env
      namespace: renovate
    type: Opaque
