apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: external-services
spec:
  externalName: 192.168.50.252
  type: ExternalName
  ports:
  - name: websecure
    port: 8006
    targetPort: 8006