apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.proxmox.russellhost.org`) # change to your domain
      kind: Rule
      services:
        - name: proxmox
          port: 8006
          scheme: https
          passHostHeader: true
    - match: Host(`proxmox.russellhost.org`) # change to your domain
      kind: Rule
      services:
        - name: proxmox
          port: 8006
          scheme: https
          passHostHeader: true
      middlewares:
        - name: default-headers
  tls:
    secretName: russellhost-tls
