apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: external-services
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8006
    targetPort: 8006
  externalIPs:
  - 192.168.50.252
