persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 15Gi
  annotations: {}
  existingClaim: "pvc-code-server"
  # hostPath: /data
extraArgs:
  - --auth
  - none
